// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/artifactengineer-landing/AppleStyle.tsx": () => import("../components/mockups/artifactengineer-landing/AppleStyle.tsx"),
  "./components/mockups/artifactengineer-landing/CinematicMinimal.tsx": () => import("../components/mockups/artifactengineer-landing/CinematicMinimal.tsx"),
  "./components/mockups/artifactengineer-landing/DashboardDense.tsx": () => import("../components/mockups/artifactengineer-landing/DashboardDense.tsx"),
  "./components/mockups/artifactengineer-landing/DocumentBuilder.tsx": () => import("../components/mockups/artifactengineer-landing/DocumentBuilder.tsx"),
  "./components/mockups/artifactengineer-landing/EditorialSplit.tsx": () => import("../components/mockups/artifactengineer-landing/EditorialSplit.tsx"),
  "./components/mockups/artifactengineer-landing/LandingPage.tsx": () => import("../components/mockups/artifactengineer-landing/LandingPage.tsx")
};
